version: "3"
services:
  rpa:
    image: structor01/rpa-gipe
    ports:
      - "8080:5000"
  painel:
    image: structor01/gipe
    ports:
      - "80:80"
  integra:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=akVLmBfN7GHhacDC
    volumes:
      - ./data/integra:/data/db
    ports:
      - "27018:27017"
  db:
    image: mongo
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
      - "27019:27017"
