version: "3"
services:
  rpa:
    image: structor01/gipe-rpa
    restart: always
    ports:
      - "8080:5000"
    links:
      - integra
  cmv:
    image: structor01/gipe-cmv
    links:
      - integra
  lc:
    image: structor01/gipe-lc
    links:
      - integra
#  painel:
#    image: structor01/gipe
#    ports:
#      - "80:80"
  integra:
    image: mongo
    restart: always
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
#      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
#      - APP_MONGO_HOST=${MONGO_HOST}
#      - MONGO_PORT=${MONGO_PORT}
#      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
#      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
#      - APP_MONGO_USER=${APP_MONGO_USER}
#      - APP_MONGO_PASS=${APP_MONGO_PASS}
#      - APP_MONGO_DB=${APP_MONGO_DB}
    volumes:
      - ./data/integra:/data/db
#      - "/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
    ports:
      - "27018:27017"
#  db:
#    image: mongo
#    restart: always
#    volumes:
#      - ./data/db:/data/db
#    ports:
#      - "27019:27017"
