version: "3"
services:
#  rpa:
#    image: structor01/gipe-rpa
#    restart: always
#    ports:
#      - "8080:5000"
#    links:
#      - integra
#  cmv:
#    image: structor01/gipe-cmv
#    ports:
#      - "3333:3333"
#    links:
#      - integra
  client:
    image: structor01/gipe-web
    links:
      - db
      - financeiro
      - vendas
    ports:
      - "80:80"
  siege:
    image: structor01/gipe-siege
    links:
      - integra
    ports:
      - "3000:3333"
  vendas:
    image: structor01/gipe-vendas
    links:
      - db
    ports:
      - "3001:3333"
  financeiro:
    image: structor01/gipe-financeiro
    links:
      - db
    ports:
      - "3002:3333"
#  lucrobruto:
#    image: structor01/gipe-lucrobruto
#    links:
#      - integra
#  painel:
#    image: structor01/gipe
#    ports:
#      - "80:80"
  integra:
    image: mongo
    restart: always
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
#      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
#      - APP_MONGO_HOST=${MONGO_HOST}
#      - MONGO_PORT=${MONGO_PORT}
#      - MONGO_ROOT_USER=${MONGO_ROOT_USERNAME}
#      - MONGO_ROOT_PASS=${MONGO_ROOT_PASSWORD}
#      - APP_MONGO_USER=${APP_MONGO_USER}
#      - APP_MONGO_PASS=${APP_MONGO_PASS}
#      - APP_MONGO_DB=${APP_MONGO_DB}
    volumes:
      - ./data/integra:/data/db
#      - "/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
    ports:
      - "27018:27017"
  redis:
    image: 'redis:latest'
    ports:
      - "6380:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
  db:
    image: mongo
    restart: always
    volumes:
      - ./client/db:/data/db
    ports:
      - "27019:27017"
