apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: vendas
  name: vendas
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: vendas
    spec:
      containers:
      - image: structor01/gipe-vendas
        name: vendas
        ports:
        - containerPort: 3333
        resources: {}
      restartPolicy: Always
status: {}
